[default.extend-words]
ba = "ba"
ot = "ot"
pn = "pn"
siz = "siz"
parm = "parm"
universite = "universite"
womens = "womens"
observ = "observ"

[default]
extend-ignore-re = [
    "np\\.\\w",
    "`eval`uable"
]

[files]
extend-exclude = ["**/_*_dict.py"]
