name: merge
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
permissions:
    contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        # Do the ones not covered in PR workflow
        os: [ubuntu, macos]
        python-version: ["3.10", "3.11"]
        test-numpy: [true]
        test-extras: [false]
        upload-coverage: [false]
        include:
          - os: windows
            python-version: "3.13"
            test-numpy: true
            test-extras: true
            upload-coverage: true
          - os: windows
            python-version: "3.14"
            test-numpy: true
            test-extras: true
            upload-coverage: false
          - os: macos
            python-version: "3.12"
            test-numpy: true
            test-extras: true
            upload-coverage: false
          - os: ubuntu
            python-version: "pypy3.10"
            test-numpy: true
            test-extras: false
            upload-coverage: false
        exclude:
          # for combo with test-extras, already includes false tests, so remove from matrix
          - os: macos
            python-version: "3.10"
            test-extras: false
    uses: ./.github/workflows/tests_wf.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      os: ${{ matrix.os }}
      python-version:  ${{ matrix.python-version }}
      test-numpy: ${{ matrix.test-numpy }}
      test-extras: ${{ matrix.test-extras }}
      upload-coverage: ${{ matrix.upload-coverage }}
