name: publish-pypi-deploy
permissions:
    contents: read

on:
  release:
    types: [ published ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.11' ]
    environment:
      name: pypi
      url: https://pypi.org/p/pydicom
    permissions:
      id-token: write
    steps:
    - name: Checkout
      # v5.0.0
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Set up Python ${{ matrix.python-version }}
      # v6.0.0
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build package
      run: |
        python -m pip install --upgrade pip
        python -m pip install flit
        flit build

    # Run tests?  Removed for now as merge into main does full testing

    - name: Upload release to PyPI
      # Note: in docs at https://github.com/pypa/gh-action-pypi-publish,
      #  it is suggested to publish in its own job, using 'needs' to
      #  ensure previous job succeeded, and artifact upload/download of
      #  the dist folder.  That seems to be related mainly to multi-OS builds,
      #  so done in same job here.
      # v1.13.0
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
